#!/bin/bash

compose_cmd=exec
service=php
user=

while getopts ":ws:u:" option; do
  case ${option} in
    w)
      compose_cmd="-f $DEVOPSY_PROJECT_DIR/compose.write.yaml run --rm"
      ;;
    s)
      service=${OPTARG}
      ;;
    u)
      user="-u ${OPTARG}"
      ;;
    :)
      echo "Option -${OPTARG} requires an argument."
      exit 1
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

# attempt to keep quotes, not 100% sure on this
_args=
for x in "${@}" ; do
    x=${x//\"/\\\"}
    x=${x//\\\\\"/\\\"}
    x="\""$x"\""
    _args=$_args" "$x
done

cmd="devopsy $compose_cmd $user $service bash $_args"
>&2 echo -e "\033[0;36mRunning '$cmd'...\033[0m"
eval $cmd
